version: '2'

services:
  mysqldata:
    image: mysql:5.7
    command: /bin/true

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword

  huginn:
    image: huginn/huginn-single-process
    restart: always
    ports:
      - 3000:3000
    links:
      - mysql
    environment:
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: myrootpassword

  huginn_threaded:
    image: huginn/huginn-single-process
    restart: always
    links:
      - mysql
    command: /scripts/init bin/threaded.rb
    environment:
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: myrootpassword
      DO_NOT_CREATE_DATABASE: "true"
      DO_NOT_MIGRATE: "true"
      DO_NOT_SEED: "true"

